/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) circle_sensitivity_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {37, 1, 1};

/* circle_sensitivity_p_global_precompute_fun:(i0[13])->(o0[37]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a1=casadi_sq(a0);
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a0=(a0+a0);
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a1=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][10]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][11]=a2;
  a3=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][12]=a3;
  a4=2.;
  a2=(a4*a2);
  if (res[0]!=0) res[0][13]=a2;
  a5=(a4*a1);
  if (res[0]!=0) res[0][14]=a5;
  a3=(a4*a3);
  if (res[0]!=0) res[0][15]=a3;
  a6=(a4*a0);
  if (res[0]!=0) res[0][16]=a6;
  a7=-2.;
  a8=(a7*a0);
  if (res[0]!=0) res[0][17]=a8;
  if (res[0]!=0) res[0][18]=a5;
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a5;
  if (res[0]!=0) res[0][21]=a3;
  if (res[0]!=0) res[0][22]=a6;
  if (res[0]!=0) res[0][23]=a8;
  if (res[0]!=0) res[0][24]=a5;
  a5=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][25]=a5;
  a0=(a0*a5);
  if (res[0]!=0) res[0][26]=a0;
  a1=(a1*a5);
  if (res[0]!=0) res[0][27]=a1;
  a5=(a4*a0);
  if (res[0]!=0) res[0][28]=a5;
  a4=(a4*a1);
  if (res[0]!=0) res[0][29]=a4;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a1;
  a7=(a7*a0);
  if (res[0]!=0) res[0][32]=a7;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a4;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real circle_sensitivity_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
