/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rect_margin_forward_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {36, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[8] = {5, 1, 0, 4, 0, 2, 3, 4};
static const casadi_int casadi_s6[3] = {1, 0, 1};

/* rect_margin_forward_constr_h_fun_jac_uxt_zt:(i0[3],i1[2],i2[0],i3[0],i4[36])->(o0,o1[5x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20;
  a00=5.0000000000000000e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=1.2000000000000000e-01;
  a03=arg[1]? arg[1][0] : 0;
  a03=(a02*a03);
  a04=arg[0]? arg[0][2] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a01=(a01+a06);
  a06=arg[4]? arg[4][0] : 0;
  a06=(a01-a06);
  a07=0.;
  a08=casadi_fmax(a06,a07);
  a09=casadi_sq(a08);
  a09=(a00*a09);
  a10=arg[4]? arg[4][1] : 0;
  a10=(a10-a01);
  a01=casadi_fmax(a10,a07);
  a11=casadi_sq(a01);
  a12=(a09*a11);
  a13=arg[0]? arg[0][1] : 0;
  a04=sin(a04);
  a14=(a03*a04);
  a13=(a13+a14);
  a14=arg[4]? arg[4][2] : 0;
  a14=(a13-a14);
  a15=casadi_fmax(a14,a07);
  a16=casadi_sq(a15);
  a17=(a12*a16);
  a18=arg[4]? arg[4][3] : 0;
  a18=(a18-a13);
  a13=casadi_fmax(a18,a07);
  a19=casadi_sq(a13);
  a20=(a17*a19);
  if (res[0]!=0) res[0][0]=a20;
  a20=(a07<=a14);
  a14=(a14<=a07);
  a14=(a20+a14);
  a20=(a20/a14);
  a15=(a15+a15);
  a12=(a12*a19);
  a15=(a15*a12);
  a20=(a20*a15);
  a15=(a07<=a18);
  a18=(a18<=a07);
  a18=(a15+a18);
  a15=(a15/a18);
  a13=(a13+a13);
  a13=(a13*a17);
  a15=(a15*a13);
  a20=(a20-a15);
  a15=(a04*a20);
  a15=(a02*a15);
  a13=(a07<=a06);
  a06=(a06<=a07);
  a06=(a13+a06);
  a13=(a13/a06);
  a08=(a08+a08);
  a16=(a16*a19);
  a11=(a11*a16);
  a00=(a00*a11);
  a08=(a08*a00);
  a13=(a13*a08);
  a08=(a07<=a10);
  a10=(a10<=a07);
  a10=(a08+a10);
  a08=(a08/a10);
  a01=(a01+a01);
  a09=(a09*a16);
  a01=(a01*a09);
  a08=(a08*a01);
  a13=(a13-a08);
  a08=(a05*a13);
  a02=(a02*a08);
  a15=(a15+a02);
  if (res[1]!=0) res[1][0]=a15;
  if (res[1]!=0) res[1][1]=a13;
  if (res[1]!=0) res[1][2]=a20;
  a20=(a03*a20);
  a05=(a05*a20);
  a03=(a03*a13);
  a04=(a04*a03);
  a05=(a05-a04);
  if (res[1]!=0) res[1][3]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rect_margin_forward_constr_h_fun_jac_uxt_zt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rect_margin_forward_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rect_margin_forward_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rect_margin_forward_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rect_margin_forward_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rect_margin_forward_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rect_margin_forward_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
