/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) circle_forward_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {26, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[27] = 
  {5, 5, 0, 5, 8, 11, 14, 19,
  0, 1, 2, 3, 4, 0, 1, 4,
  0, 2, 4, 0, 3, 4, 0, 1,
  2, 3, 4};
static const casadi_int casadi_s7[3] = {0, 0, 1};
static const casadi_int casadi_s8[3] = {0, 5, 1};

/* circle_forward_cost_ext_cost_0_fun_jac_hess:(i0[3],i1[2],i2[0],i3[0],i4[26])->(o0,o1[5],o2[5x5,19nz],o3[],o4[0x5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[4]? arg[4][6] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=1.2000000000000000e-01;
  a03=arg[1]? arg[1][0] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][2] : 0;
  a06=cos(a05);
  a07=(a04*a06);
  a01=(a01+a07);
  a08=arg[4]? arg[4][4] : 0;
  a01=(a01-a08);
  a08=casadi_sq(a01);
  a09=arg[0]? arg[0][1] : 0;
  a10=sin(a05);
  a11=(a04*a10);
  a09=(a09+a11);
  a12=arg[4]? arg[4][5] : 0;
  a09=(a09-a12);
  a12=casadi_sq(a09);
  a08=(a08+a12);
  a08=(a00*a08);
  a12=arg[4]? arg[4][8] : 0;
  a13=arg[1]? arg[1][1] : 0;
  a14=tan(a13);
  a15=(a04*a14);
  a16=4.5000000000000001e-01;
  a15=(a15/a16);
  a05=(a05+a15);
  a15=arg[4]? arg[4][7] : 0;
  a05=(a05-a15);
  a15=sin(a05);
  a05=cos(a05);
  a16=atan2(a15,a05);
  a17=casadi_sq(a16);
  a17=(a12*a17);
  a08=(a08+a17);
  a17=arg[4]? arg[4][9] : 0;
  a18=casadi_sq(a03);
  a18=(a17*a18);
  a08=(a08+a18);
  a18=arg[4]? arg[4][10] : 0;
  a19=casadi_sq(a13);
  a19=(a18*a19);
  a08=(a08+a19);
  if (res[0]!=0) res[0][0]=a08;
  a03=(a03+a03);
  a03=(a03*a17);
  a17=2.2222222222222223e+00;
  a16=(a16+a16);
  a16=(a16*a12);
  a08=(a15*a16);
  a19=(a15*a08);
  a20=(a05*a16);
  a21=(a05*a20);
  a19=(a19+a21);
  a21=(a17*a19);
  a22=(a14*a21);
  a22=(a02*a22);
  a03=(a03+a22);
  a09=(a09+a09);
  a09=(a09*a00);
  a22=(a10*a09);
  a22=(a02*a22);
  a03=(a03+a22);
  a01=(a01+a01);
  a01=(a01*a00);
  a22=(a06*a01);
  a22=(a02*a22);
  a03=(a03+a22);
  if (res[1]!=0) res[1][0]=a03;
  a03=(a13+a13);
  a03=(a03*a18);
  a18=(a04*a21);
  a22=cos(a13);
  a23=casadi_sq(a22);
  a18=(a18/a23);
  a03=(a03+a18);
  if (res[1]!=0) res[1][1]=a03;
  if (res[1]!=0) res[1][2]=a01;
  if (res[1]!=0) res[1][3]=a09;
  a03=(a04*a09);
  a24=(a06*a03);
  a19=(a19+a24);
  a24=(a04*a01);
  a25=(a10*a24);
  a19=(a19-a25);
  if (res[1]!=0) res[1][4]=a19;
  a19=arg[4]? arg[4][11] : 0;
  a25=(a02*a14);
  a25=(a17*a25);
  a26=(a05*a25);
  a27=(a08*a26);
  a28=(a16*a26);
  a26=(a05*a26);
  a25=(a15*a25);
  a29=(a15*a25);
  a26=(a26+a29);
  a26=(a26+a26);
  a26=(a12*a26);
  a29=(a15*a26);
  a28=(a28+a29);
  a28=(a15*a28);
  a27=(a27+a28);
  a26=(a05*a26);
  a28=(a16*a25);
  a26=(a26-a28);
  a26=(a05*a26);
  a25=(a20*a25);
  a26=(a26-a25);
  a27=(a27+a26);
  a27=(a17*a27);
  a26=(a14*a27);
  a26=(a02*a26);
  a19=(a19+a26);
  a26=(a02*a10);
  a26=(a26+a26);
  a26=(a00*a26);
  a25=(a10*a26);
  a25=(a02*a25);
  a19=(a19+a25);
  a25=(a02*a06);
  a25=(a25+a25);
  a25=(a00*a25);
  a28=(a06*a25);
  a28=(a02*a28);
  a19=(a19+a28);
  if (res[2]!=0) res[2][0]=a19;
  a21=(a02*a21);
  a27=(a04*a27);
  a21=(a21+a27);
  a21=(a21/a23);
  if (res[2]!=0) res[2][1]=a21;
  if (res[2]!=0) res[2][2]=a25;
  if (res[2]!=0) res[2][3]=a26;
  a27=(a08*a05);
  a19=(a16*a05);
  a28=arg[4]? arg[4][12] : 0;
  a29=(a15*a28);
  a19=(a19+a29);
  a19=(a15*a19);
  a27=(a27+a19);
  a28=(a05*a28);
  a19=(a16*a15);
  a28=(a28-a19);
  a28=(a05*a28);
  a19=(a20*a15);
  a28=(a28-a19);
  a27=(a27+a28);
  a28=(a17*a27);
  a14=(a14*a28);
  a14=(a02*a14);
  a09=(a09*a06);
  a07=(a07+a07);
  a07=(a00*a07);
  a19=(a10*a07);
  a09=(a09+a19);
  a09=(a02*a09);
  a14=(a14+a09);
  a01=(a01*a10);
  a11=(a11+a11);
  a00=(a00*a11);
  a11=(a06*a00);
  a01=(a01+a11);
  a02=(a02*a01);
  a14=(a14-a02);
  if (res[2]!=0) res[2][4]=a14;
  if (res[2]!=0) res[2][5]=a21;
  a21=arg[4]? arg[4][13] : 0;
  a02=(a04/a23);
  a02=(a17*a02);
  a01=(a05*a02);
  a08=(a08*a01);
  a11=(a16*a01);
  a01=(a05*a01);
  a02=(a15*a02);
  a09=(a15*a02);
  a01=(a01+a09);
  a01=(a01+a01);
  a12=(a12*a01);
  a01=(a15*a12);
  a11=(a11+a01);
  a15=(a15*a11);
  a08=(a08+a15);
  a12=(a05*a12);
  a16=(a16*a02);
  a12=(a12-a16);
  a05=(a05*a12);
  a20=(a20*a02);
  a05=(a05-a20);
  a08=(a08+a05);
  a17=(a17*a08);
  a17=(a04*a17);
  a17=(a17/a23);
  a18=(a18/a23);
  a22=(a22+a22);
  a13=sin(a13);
  a22=(a22*a13);
  a18=(a18*a22);
  a17=(a17+a18);
  a21=(a21+a17);
  if (res[2]!=0) res[2][6]=a21;
  a28=(a04*a28);
  a28=(a28/a23);
  if (res[2]!=0) res[2][7]=a28;
  if (res[2]!=0) res[2][8]=a25;
  a25=arg[4]? arg[4][14] : 0;
  if (res[2]!=0) res[2][9]=a25;
  a23=(-a00);
  if (res[2]!=0) res[2][10]=a23;
  if (res[2]!=0) res[2][11]=a26;
  if (res[2]!=0) res[2][12]=a25;
  if (res[2]!=0) res[2][13]=a07;
  if (res[2]!=0) res[2][14]=a14;
  if (res[2]!=0) res[2][15]=a28;
  if (res[2]!=0) res[2][16]=a23;
  if (res[2]!=0) res[2][17]=a07;
  a07=(a04*a07);
  a07=(a06*a07);
  a03=(a03*a10);
  a07=(a07-a03);
  a27=(a27+a07);
  a24=(a24*a06);
  a04=(a04*a00);
  a10=(a10*a04);
  a24=(a24-a10);
  a27=(a27-a24);
  if (res[2]!=0) res[2][18]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_forward_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_forward_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void circle_forward_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void circle_forward_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int circle_forward_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int circle_forward_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real circle_forward_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_forward_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_forward_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_forward_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_forward_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_forward_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
