/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) circle_sensitivity_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {37, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[13] = 
  {5, 5, 0, 1, 2, 3, 4, 5,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s7[3] = {0, 0, 1};
static const casadi_int casadi_s8[3] = {0, 5, 1};

/* circle_sensitivity_cost_ext_cost_fun_jac_hess:(i0[3],i1[2],i2[0],i3[0],i4[37])->(o0,o1[5],o2[5x5,5nz],o3[],o4[0x5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=arg[4]? arg[4][8] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[4]? arg[4][6] : 0;
  a01=(a01-a02);
  a02=casadi_sq(a01);
  a03=arg[0]? arg[0][1] : 0;
  a04=arg[4]? arg[4][7] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a02=(a02+a04);
  a02=(a00*a02);
  a04=arg[4]? arg[4][10] : 0;
  a05=arg[0]? arg[0][2] : 0;
  a06=arg[4]? arg[4][9] : 0;
  a05=(a05-a06);
  a06=sin(a05);
  a05=cos(a05);
  a07=atan2(a06,a05);
  a08=casadi_sq(a07);
  a08=(a04*a08);
  a02=(a02+a08);
  a08=arg[4]? arg[4][11] : 0;
  a09=arg[1]? arg[1][0] : 0;
  a10=casadi_sq(a09);
  a10=(a08*a10);
  a02=(a02+a10);
  a10=arg[4]? arg[4][12] : 0;
  a11=arg[1]? arg[1][1] : 0;
  a12=casadi_sq(a11);
  a12=(a10*a12);
  a02=(a02+a12);
  if (res[0]!=0) res[0][0]=a02;
  a09=(a09+a09);
  a09=(a09*a08);
  if (res[1]!=0) res[1][0]=a09;
  a11=(a11+a11);
  a11=(a11*a10);
  if (res[1]!=0) res[1][1]=a11;
  a01=(a01+a01);
  a01=(a01*a00);
  if (res[1]!=0) res[1][2]=a01;
  a03=(a03+a03);
  a03=(a03*a00);
  if (res[1]!=0) res[1][3]=a03;
  a07=(a07+a07);
  a07=(a07*a04);
  a04=(a06*a07);
  a03=(a06*a04);
  a00=(a05*a07);
  a01=(a05*a00);
  a03=(a03+a01);
  if (res[1]!=0) res[1][4]=a03;
  a03=arg[4]? arg[4][19] : 0;
  if (res[2]!=0) res[2][0]=a03;
  a03=arg[4]? arg[4][20] : 0;
  if (res[2]!=0) res[2][1]=a03;
  a03=arg[4]? arg[4][21] : 0;
  if (res[2]!=0) res[2][2]=a03;
  if (res[2]!=0) res[2][3]=a03;
  a04=(a04*a05);
  a03=(a07*a05);
  a01=arg[4]? arg[4][22] : 0;
  a11=(a06*a01);
  a03=(a03+a11);
  a03=(a06*a03);
  a04=(a04+a03);
  a01=(a05*a01);
  a07=(a07*a06);
  a01=(a01-a07);
  a05=(a05*a01);
  a00=(a00*a06);
  a05=(a05-a00);
  a04=(a04+a05);
  if (res[2]!=0) res[2][4]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_cost_ext_cost_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real circle_sensitivity_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
