/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) circle_sensitivity_constr_h_jac_p_hess_xu_p_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {37, 1, 1};
static const casadi_int casadi_s5[18] = 
  {1, 13, 0, 0, 0, 0, 0, 0,
  1, 2, 2, 2, 2, 2, 2, 2,
  0, 0};
static const casadi_int casadi_s6[19] = 
  {5, 13, 0, 0, 0, 0, 0, 0,
  0, 3, 3, 3, 3, 3, 3, 3,
  0, 3, 4};

/* circle_sensitivity_constr_h_jac_p_hess_xu_p:(i0[3],i1[2],i2,i3[0],i4[0],i5[37])->(o0[1x13,2nz],o1[5x13,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[5]? arg[5][4] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a1=1.2000000000000000e-01;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a1*a2);
  a3=arg[0]? arg[0][2] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a0=(a0+a5);
  a5=arg[5]? arg[5][0] : 0;
  a0=(a0-a5);
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=-2.;
  a5=arg[2]? arg[2][0] : 0;
  a0=(a0*a5);
  a4=(a4*a0);
  a1=(a1*a4);
  a1=(-a1);
  if (res[1]!=0) res[1][0]=a1;
  a1=(-a0);
  if (res[1]!=0) res[1][1]=a1;
  a3=cos(a3);
  a2=(a2*a0);
  a3=(a3*a2);
  a3=(-a3);
  if (res[1]!=0) res[1][2]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_constr_h_jac_p_hess_xu_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_constr_h_jac_p_hess_xu_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_constr_h_jac_p_hess_xu_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void circle_sensitivity_constr_h_jac_p_hess_xu_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_constr_h_jac_p_hess_xu_p_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int circle_sensitivity_constr_h_jac_p_hess_xu_p_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real circle_sensitivity_constr_h_jac_p_hess_xu_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_constr_h_jac_p_hess_xu_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* circle_sensitivity_constr_h_jac_p_hess_xu_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_constr_h_jac_p_hess_xu_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* circle_sensitivity_constr_h_jac_p_hess_xu_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int circle_sensitivity_constr_h_jac_p_hess_xu_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
