/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rect_margin_forward_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {36, 1, 1};
static const casadi_int casadi_s4[15] = 
  {5, 3, 0, 3, 6, 9, 0, 2,
  4, 0, 3, 4, 0, 1, 4};
static const casadi_int casadi_s5[14] = 
  {5, 5, 0, 2, 4, 4, 4, 6,
  1, 4, 0, 1, 0, 4};

/* rect_margin_forward_dyn_disc_phi_fun_jac_hess:(i0[3],i1[2],i2[3],i3[0],i4[36])->(o0[3],o1[5x3,9nz],o2[5x5,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.2000000000000000e-01;
  a02=arg[1]? arg[1][0] : 0;
  a02=(a01*a02);
  a03=arg[0]? arg[0][2] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a00=(a00+a05);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a06=sin(a03);
  a07=(a02*a06);
  a00=(a00+a07);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a08=tan(a00);
  a09=(a02*a08);
  a10=4.5000000000000001e-01;
  a09=(a09/a10);
  a03=(a03+a09);
  if (res[0]!=0) res[0][2]=a03;
  a03=(a01*a04);
  if (res[1]!=0) res[1][0]=a03;
  a03=1.;
  if (res[1]!=0) res[1][1]=a03;
  a07=(-a07);
  if (res[1]!=0) res[1][2]=a07;
  a07=(a01*a06);
  if (res[1]!=0) res[1][3]=a07;
  if (res[1]!=0) res[1][4]=a03;
  if (res[1]!=0) res[1][5]=a05;
  a05=2.2222222222222223e+00;
  a08=(a01*a08);
  a08=(a05*a08);
  if (res[1]!=0) res[1][6]=a08;
  a08=cos(a00);
  a07=casadi_sq(a08);
  a09=(a02/a07);
  a09=(a05*a09);
  if (res[1]!=0) res[1][7]=a09;
  if (res[1]!=0) res[1][8]=a03;
  a03=arg[2]? arg[2][2] : 0;
  a05=(a05*a03);
  a03=(a01*a05);
  a03=(a03/a07);
  if (res[2]!=0) res[2][0]=a03;
  a09=arg[2]? arg[2][1] : 0;
  a10=(a01*a09);
  a10=(a04*a10);
  a11=arg[2]? arg[2][0] : 0;
  a01=(a01*a11);
  a01=(a06*a01);
  a10=(a10-a01);
  if (res[2]!=0) res[2][1]=a10;
  if (res[2]!=0) res[2][2]=a03;
  a05=(a02*a05);
  a05=(a05/a07);
  a05=(a05/a07);
  a08=(a08+a08);
  a00=sin(a00);
  a08=(a08*a00);
  a05=(a05*a08);
  if (res[2]!=0) res[2][3]=a05;
  if (res[2]!=0) res[2][4]=a10;
  a09=(a02*a09);
  a09=(a09*a06);
  a02=(a02*a11);
  a02=(a02*a04);
  a09=(a09+a02);
  a09=(-a09);
  if (res[2]!=0) res[2][5]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void rect_margin_forward_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rect_margin_forward_dyn_disc_phi_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rect_margin_forward_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rect_margin_forward_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rect_margin_forward_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rect_margin_forward_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rect_margin_forward_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rect_margin_forward_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rect_margin_forward_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
